### PR TITLE
Fixing polling problem

### LINKED ISSUE #104: Status VIPs not working in v5.6.6
Reported by Evan via Discord. Needs investigations.

### PR DESCRIPTION
**Pull request by epacke**
Fixes #104

### CODE REVIEW

**Comment by timriker** [comment]
Uncaught TypeError: data.memberstatuses.forEach is not a function
    at Object.success (bigipreport.js:1351:49)
    at c (jquery.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29072)
    at l (jquery.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)

**Review by timriker — APPROVED** [review]
Looks good now. Thanks!
